In [1]:
# pip install pandas

In [2]:
a=[1,2,3,4,5,6,7,12,8]
for i in a:
  print(i, end =" ")

1 2 3 4 5 6 7 12 8 

In [3]:
#pandas
import pandas as pd
dict = {
    "name":['shiva','anish','python'],
    'marks':[10,20,30],
    'internal':[20,12,20],
    'external':[100,23,100]
    }
print(dict)
df=pd.DataFrame(dict)
print(df)

{'name': ['shiva', 'anish', 'python'], 'marks': [10, 20, 30], 'internal': [20, 12, 20], 'external': [100, 23, 100]}
     name  marks  internal  external
0   shiva     10        20       100
1   anish     20        12        23
2  python     30        20       100


In [4]:
#pandas
import pandas as pd
dict = {
    "name":['shiva','anish','python'],
    'marks':[10,20,30],
    'internal':[20,12,20],
    'external':[100,23,100]
    }
print(dict)
df=pd.DataFrame(dict)
df.index=[202211,202212,202213]
print(df)

{'name': ['shiva', 'anish', 'python'], 'marks': [10, 20, 30], 'internal': [20, 12, 20], 'external': [100, 23, 100]}
          name  marks  internal  external
202211   shiva     10        20       100
202212   anish     20        12        23
202213  python     30        20       100


In [5]:
df.to_csv('dict.csv')

In [6]:
df.head()

name  marks  internal  external
202211   shiva     10        20       100
202212   anish     20        12        23
202213  python     30        20       100

In [7]:
#Add a row in the DataFrame
df.loc[len(df.index)] = ['Amy2', 89, 93,70]
display(df)
df.loc[len(df.index)] = ['Amy1', 89, 93,40]
display(df)

name  marks  internal  external
202211   shiva     10        20       100
202212   anish     20        12        23
202213  python     30        20       100
3         Amy2     89        93        70

name  marks  internal  external
202211   shiva     10        20       100
202212   anish     20        12        23
202213  python     30        20       100
3         Amy2     89        93        70
4         Amy1     89        93        40

In [8]:
# Using DataFrame.insert() to add a column
#df.insert(location,'name of column',values,allow duplicates)

df.insert(2, "Age", [21, 23, 24, 21,25], True)

# Observe the result
print(df)

          name  marks  Age  internal  external
202211   shiva     10   21        20       100
202212   anish     20   23        12        23
202213  python     30   24        20       100
3         Amy2     89   21        93        70
4         Amy1     89   25        93        40


In [9]:
#Add a row in the DataFrame
df.loc[len(df.index)] = ['Amy2', 89, 93,70,40]
display(df)
df.loc[len(df.index)] = ['Amy1', 89, 93,40,53]
display(df)

name  marks  Age  internal  external
202211   shiva     10   21        20       100
202212   anish     20   23        12        23
202213  python     30   24        20       100
3         Amy2     89   21        93        70
4         Amy1     89   25        93        40
5         Amy2     89   93        70        40

name  marks  Age  internal  external
202211   shiva     10   21        20       100
202212   anish     20   23        12        23
202213  python     30   24        20       100
3         Amy2     89   21        93        70
4         Amy1     89   25        93        40
5         Amy2     89   93        70        40
6         Amy1     89   93        40        53

In [10]:
df

name  marks  Age  internal  external
202211   shiva     10   21        20       100
202212   anish     20   23        12        23
202213  python     30   24        20       100
3         Amy2     89   21        93        70
4         Amy1     89   25        93        40
5         Amy2     89   93        70        40
6         Amy1     89   93        40        53

In [11]:
df.tail()

name  marks  Age  internal  external
202213  python     30   24        20       100
3         Amy2     89   21        93        70
4         Amy1     89   25        93        40
5         Amy2     89   93        70        40
6         Amy1     89   93        40        53

In [12]:
df.index=['f1','f2','f3','f4','f5','f6','f7']

In [13]:
print(df)

      name  marks  Age  internal  external
f1   shiva     10   21        20       100
f2   anish     20   23        12        23
f3  python     30   24        20       100
f4    Amy2     89   21        93        70
f5    Amy1     89   25        93        40
f6    Amy2     89   93        70        40
f7    Amy1     89   93        40        53


In [14]:
#Delete a column
df=df.drop(columns=["name"])
df

marks  Age  internal  external
f1     10   21        20       100
f2     20   23        12        23
f3     30   24        20       100
f4     89   21        93        70
f5     89   25        93        40
f6     89   93        70        40
f7     89   93        40        53

In [15]:
#delete a row
df=df.drop(df.index[3])
df

marks  Age  internal  external
f1     10   21        20       100
f2     20   23        12        23
f3     30   24        20       100
f5     89   25        93        40
f6     89   93        70        40
f7     89   93        40        53

In [16]:
df.marks

f1    10
f2    20
f3    30
f5    89
f6    89
f7    89
Name: marks, dtype: int64

In [17]:
df['marks']

f1    10
f2    20
f3    30
f5    89
f6    89
f7    89
Name: marks, dtype: int64

In [18]:
#print a specific row as per index
print(df.loc['f1'])

marks        10
Age          21
internal     20
external    100
Name: f1, dtype: int64


In [19]:
#numpy
import numpy as np

In [20]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [21]:
arr=np.array([1,2,3],dtype=float)
print(arr)

[1. 2. 3.]


In [22]:
#numpy N_dimensional array
ar=np.array([[1,2,3,4],
             [1,2,3,4],
             [1,2,3,4],
             [1,2,3,4]])

In [23]:
print(ar)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [24]:
import numpy as np
fruit_cost=[10,60,90,40,50]
vegetable_cost=[10,20,30,40,50]
combine_np=np.array([fruit_cost,vegetable_cost])
print(combine_np)

[[10 60 90 40 50]
 [10 20 30 40 50]]


In [25]:
#subsetting numpy array
ar1=np.array([1,2,3,4,5,6,7,8,9,10])
print(ar1[ar1>5])

[ 6  7  8  9 10]


In [26]:
#Scipy--Stands for Scientific Python
from scipy.special import exp10
val = exp10([5,10])
#Output : [1.e+01 1.e+10]
print(val)

ModuleNotFoundError: No module named 'scipy'

In [ ]:
from scipy.special import cbrt
num = cbrt(27)
#Output : 3.0
print(num)

In [ ]:
from scipy.special import perm
permutation = perm(4,2)
#Output: 12.0
print(permutation)

In [ ]:
from scipy.special import comb
combination = comb(4,2)
#Output: 6.0
print(combination)

In [ ]:
#linear algebra
from scipy import linalg
import numpy as np
#define square matrix
arr = np.array([ [1,2], [3,4] ])
#calculate the determinant
determinant = linalg.det(arr)
#Output: -2.0
print(determinant)

In [ ]:
#Calculating the inverse of a 2-D matrix:
from scipy import linalg
import numpy as np
#define square matrix
arr = np.array([ [6,7], [4,5] ])
#calculate the inverse
inverse = linalg.inv(arr)
#Output: [[ 2.5 -3.5]
# [-2. 3. ]]
print(inverse)

In [ ]:
#matplotlib

In [ ]:
from matplotlib import pyplot as plt
#Creating the plot
plt.plot([1,2,3],[1,2,3])
#Printing the created plot
plt.show()

In [ ]:
from matplotlib import pyplot as plt
#Creating the plot
plt.scatter([1,2,3],[1,2,3])
#Printing the created plot
plt.show()

In [ ]:
from matplotlib import pyplot as plt
#Creating the plot
plt.plot([1,2,3],[1,2,3],label='k')
plt.plot([1,2,3],[4,5,6],label='i',color='r')
plt.legend()
plt.xlabel('item')
plt.ylabel('kind')
#Printing the created plot
plt.show()

In [ ]:
#Bar Chart
from matplotlib import pyplot as plt
plt.bar([1,2,3,4],[10,30,60,90])
plt.xlabel('Season')
plt.ylabel('Price')
plt.title('Fruit Season')
plt.show()

In [ ]:
from matplotlib import pyplot as plt
plt.bar([1,2,3,4],[10,30,60,90],label="mango",width=.5)
plt.bar([1,2,3,4],[10,30,60,90],label="apple",color='r',width=.2)
plt.legend()
plt.xlabel('Season')
plt.ylabel('Price')
plt.title('Fruit Season')
plt.show()

In [ ]:
from matplotlib import pyplot as plt
price_season = [1,10,2,20,3,30,4,45,5,65,43,54,57,87,65,34,85,37,56,75,98,99,26,29,35,42,46,53,67,68]
bins = [0,10,20,30,40,50,60,70,80,90,100]
plt.hist(price_season, bins, histtype='bar', rwidth=0.7)
plt.xlabel('price groups')
plt.ylabel('price of fruits')
plt.title('example histogram')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
x = [2,1,3,4,2,5,4,3,6,2]
y = [6,5,6.5,3,7,8.5,9,3.5,4.3,8.1]
x1=[8,2.5,7,9.5,11,10.2,13]
y1=[3,2.4,3.6,5,4.4,6,5.3]
plt.scatter(x,y, label='example 1',color='g')
plt.scatter(x1,y1,label='example2',color='b')
plt.xlabel('example1')
plt.ylabel('example2')
plt.title('Scatter Plot')
plt.legend()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
x = [2,1,3,4,2,5,4,3,6,2]
y = [6,5,6.5,3,7,8.5,9,3.5,4.3,8.1]
plt.scatter(x,y)
plt.xlabel('fruit')
plt.ylabel('price')
plt.title('price vs quanity')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
x = [2,1,3,4,2,5,4,3,6,2]
y = [6,5,6.5,3,7,8.5,9,3.5,4.3,8.1]
x1 = [2.2,1.3,3.4,4.5,1.2,2.5,2.4,3.7,6.5,1.2]
y1 = [6,5,6.5,3,7,8.5,9,3.5,4.3,8.1]
plt.scatter(x,y,label='apple')
plt.scatter(x1,y1,label='banana',color='r')
plt.xlabel('fruit')
plt.ylabel('price')
plt.legend()
plt.title('price vs quanity')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
slices = [6,3,4,12]
breakast_options = ['Fruits','Cereal','Milk','poha']
plt.pie(slices,labels=breakast_options,autopct='%1.1f%%')
plt.title('Breakfast Preferences')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
slices = [6,3,4,12]
plt.pie(slices)
plt.show()

In [ ]:
#Seaborn
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
# Load the "tips" dataset
df = sns.load_dataset("tips")
df.head()


In [ ]:
# Create violinplot using seaborn
sns.violinplot(data=df)
# Show the plot
plt.show()

In [ ]:
df=df.drop(columns=["time"])


In [ ]:
df.head()

In [ ]:
# Create violinplot using seaborn
sns.violinplot(data=df)
# Show the plot
plt.show()

In [ ]:
#scatter plot
import matplotlib.pyplot as plt
import seaborn as sns
# Load the "tips" dataset
df = sns.load_dataset("tips")
#Creating a scatter plot with hue(colour) to one of the variables
sns.relplot(x="total_bill", y="tip", hue="day", data=df);
# Show the plot
plt.show()

In [ ]:
from __future__ import print_function
import torch
#Construct a matrix using torch
matrix = torch.empty(4,2)
print(matrix)
#Construct a random matrix using torch
matrix_rand = torch.rand(4,2)
print(matrix_rand)