In [ ]:
#pandas Installation
#data frame is just and row and column 

In [ ]:
pip install pandas

In [1]:
#import pandas 
import pandas as pd

# Create a Data Frame using pandas for the following dictionary

thisdict = {
  "brand": ["Ford","tata","mahindra"],
  "model": ["Mustang","nexon", "scorpioa"],
  "year": [1964,2010,2009]
}
thisdict

{'brand': ['Ford', 'tata', 'mahindra'],
 'model': ['Mustang', 'nexon', 'scorpioa'],
 'year': [1964, 2010, 2009]}

In [2]:
df=pd.DataFrame(thisdict)

In [3]:
df

brand     model  year
0      Ford   Mustang  1964
1      tata     nexon  2010
2  mahindra  scorpioa  2009

In [4]:
df.index=['m1','m2','m3']

In [5]:
print(df)

       brand     model  year
m1      Ford   Mustang  1964
m2      tata     nexon  2010
m3  mahindra  scorpioa  2009


In [6]:
#csv file 
df.to_csv("data.csv")

PermissionError: [Errno 13] Permission denied: 'data.csv'

In [9]:
#insert evement in a row
df.loc[len(df.index)]=['shiva','f1', 2023]

In [10]:
df

brand     model  year
m1      Ford   Mustang  1964
m2      tata     nexon  2010
m3  mahindra  scorpioa  2009
3      shiva        f1  2023

In [11]:
#insert rows
df.loc[len(df.index)]=['shiva','f1', 2023]
df.loc[len(df.index)]=['shiva1','f1.1', 2023]
df.loc[len(df.index)]=['shiva2','f1.2', 2023]
df.loc[len(df.index)]=['shiva3','f1.3', 2023]

In [12]:
df

brand     model  year
m1      Ford   Mustang  1964
m2      tata     nexon  2010
m3  mahindra  scorpioa  2009
3      shiva        f1  2023
4      shiva        f1  2023
5     shiva1      f1.1  2023
6     shiva2      f1.2  2023
7     shiva3      f1.3  2023

In [13]:
df.tail(6)

brand     model  year
m3  mahindra  scorpioa  2009
3      shiva        f1  2023
4      shiva        f1  2023
5     shiva1      f1.1  2023
6     shiva2      f1.2  2023
7     shiva3      f1.3  2023

In [20]:
df.insert(1,"xyz12",[1,2,3,4,5,6,8,8])

In [21]:
df

brand  xyz12  xyz1  xyz     model  year
m1      Ford      1     1    1   Mustang  1964
m2      tata      2     2    2     nexon  2010
m3  mahindra      3     3    3  scorpioa  2009
3      shiva      4     4    4        f1  2023
4      shiva      5     5    5        f1  2023
5     shiva1      6     6    6      f1.1  2023
6     shiva2      8     8    7      f1.2  2023
7     shiva3      8     8    8      f1.3  2023

In [23]:
df.loc[len(df.index)]=['shiva','f1', 2023,2,3,3]

In [24]:
df

brand xyz12  xyz1  xyz     model  year
m1      Ford     1     1    1   Mustang  1964
m2      tata     2     2    2     nexon  2010
m3  mahindra     3     3    3  scorpioa  2009
3      shiva     4     4    4        f1  2023
4      shiva     5     5    5        f1  2023
5     shiva1     6     6    6      f1.1  2023
6     shiva2     8     8    7      f1.2  2023
7     shiva3     8     8    8      f1.3  2023
8      shiva    f1  2023    2         3     3

In [27]:
df=df.drop(columns=['xyz1','xyz12'])

In [28]:
df

brand     model  year
m1      Ford   Mustang  1964
m2      tata     nexon  2010
m3  mahindra  scorpioa  2009
3      shiva        f1  2023
4      shiva        f1  2023
5     shiva1      f1.1  2023
6     shiva2      f1.2  2023
7     shiva3      f1.3  2023
8      shiva         3     3

In [29]:
df=df.drop(df.index[3])

In [30]:
df

brand     model  year
m1      Ford   Mustang  1964
m2      tata     nexon  2010
m3  mahindra  scorpioa  2009
4      shiva        f1  2023
5     shiva1      f1.1  2023
6     shiva2      f1.2  2023
7     shiva3      f1.3  2023
8      shiva         3     3

In [31]:
df=df.drop(df.index[2])

In [32]:
df

brand    model  year
m1    Ford  Mustang  1964
m2    tata    nexon  2010
4    shiva       f1  2023
5   shiva1     f1.1  2023
6   shiva2     f1.2  2023
7   shiva3     f1.3  2023
8    shiva        3     3

In [33]:
df.brand

m1      Ford
m2      tata
4      shiva
5     shiva1
6     shiva2
7     shiva3
8      shiva
Name: brand, dtype: object

In [34]:
df.loc['m1']

brand       Ford
model    Mustang
year        1964
Name: m1, dtype: object

In [35]:
#numpy array


In [36]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:
import numpy as np1
array1 = np1.array([1,2,3,4])

In [38]:
array1

array([1, 2, 3, 4])

In [41]:
array2 = np1.array([[1,2,3,4],
                  [1,2,3,4],
                  [1,2,3,4]])

In [42]:
array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [43]:
list1=[1,2,3,4]
list2=[1,2,3,4]
array3=np1.array([list1,list2])

In [44]:
array3

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [46]:
print(array2[array2<3])

[1 2 1 2 1 2]


In [47]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [48]:
from scipy.special import exp10
from scipy.special import cbrt
from scipy.special import perm
from scipy.special import comb

val=exp10(5)



In [49]:
val

100000.0

In [50]:
num=cbrt(27)

In [51]:
num

3.0

In [52]:
num = perm(9,2)

In [53]:
num

72.0

In [55]:
num = comb(9,2)
num

36.0

In [56]:
#scipy for linear algebra

In [57]:
from scipy import linalg
import numpy as np

In [64]:
array2 = np.array([[5,1,3],
                  [8,7,2],
                  [9,2,3]])

In [65]:
det=linalg.det(array2)

In [66]:
det

-62.000000000000014

In [67]:
invv=linalg.inv(array2)

In [68]:
invv

array([[-0.27419355, -0.0483871 ,  0.30645161],
       [ 0.09677419,  0.19354839, -0.22580645],
       [ 0.75806452,  0.01612903, -0.43548387]])